
name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:

    - uses: actions/checkout@v1

    - if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install gfortran

    - if: matrix.os == 'macOS-latest'
      run: |
        brew install gcc
        brew reinstall gcc

    - name: Clean, build, and test
      run: |

        git submodule update --init --recursive
        #bash ./test.sh

        # Build core LAPACK libs

        pushd submodules/lapack

        # Use default config (for gfortran)
        cp make.inc.example make.inc

        make blaslib
        make lib

        ## Careful:  no "ls" on Windows
        #ls -ltrh

        # From submodules/lapack
        popd

        # Build our program
        gfortran main.f90 -o main -L submodules/lapack submodules/lapack/liblapack.a submodules/lapack/librefblas.a

    #- name: Upload artifact
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: factory-0-0-1
    #    path: inputs/frames/factory_100.pbm

