
name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:

    - uses: actions/checkout@v1

    - if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install gfortran

    - if: matrix.os == 'macOS-latest'
      run: |
        brew install gcc
        brew reinstall gcc

    - name: Checkout submodules
      run: |

        git submodule update --init --recursive

    - name: Build core LAPACK libs
      run: |

        pushd submodules/lapack

        # Use default config (for gfortran)
        cp make.inc.example make.inc

        # Only these libs are required
        make blaslib
        make lib

        ## Careful:  no "ls" on Windows
        #ls -ltrh

        # From submodules/lapack
        popd

    - name: Upload LAPACK artifacts
      uses: actions/upload-artifact@v2
      with:
        name: lapack-3-10-0
        path: |
          submodules/lapack/liblapack.a
          submodules/lapack/librefblas.a

    - name: Build and test
      run: |

        gfortran main.f90 -o main submodules/lapack/liblapack.a submodules/lapack/librefblas.a

        ./main

